function AboutUs() {
  return (
    <div className="">
      <img
        src="/aboutus-hero.svg"
        alt="about-us"
        className="h-[300px] mx-auto"
      />
      <div className="text-center">
        <div className="text-black text-3xl font-medium my-5">What we do?</div>
        <p>
          Welcome to Helpify, your go-to platform for staying updated on what's
          happening in your locality or city! We understand the importance of
          being connected to the pulse of your community, which is why we've
          created a unique platform that revolves around your location. At
          Helpify, we believe that every community has its own stories, events,
          and voices waiting to be heard. Our mission is to bridge the gap
          between you and your neighborhood, providing you with a seamless
          experience to discover, engage, and connect with the happenings around
          you. With our innovative approach, we utilize advanced location-based
          technology to curate a personalized feed of posts, events, and updates
          specifically tailored to your area. Whether you're interested in local
          news, events, or simply want to connect with fellow residents, our
          platform empowers you to explore and engage with your community like
          never before. Here's how it works: By simply inputting your location,
          you unlock a treasure trove of relevant content generated by people in
          your vicinity. From neighborhood gatherings and local businesses to
          community initiatives and discussions, you'll never miss out on what's
          trending in your area. But Helpify is more than just a news
          aggregator—it's a vibrant community hub where you can share your own
          stories, insights, and experiences with your neighbors. Whether you're
          a resident, business owner, or community organizer, our platform
          provides you with a voice to connect and contribute to the collective
          narrative of your locality. Join us in fostering a sense of belonging
          and unity within your neighborhood. Explore Helpify today and discover
          the heartbeat of your community, one post at a time. Stay connected.
          Stay informed.
        </p>

        <p className="italic font-medium mt-5">Stay local with Helpify.</p>
      </div>
    </div>
  );
}

export default AboutUs;
